all: alloclots burncycles

alloclots: alloclots.cc
	g++ -Wall -Wextra -pedantic -std=c++11 -O3 -g -o alloclots alloclots.cc

burncycles: burncycles.cc
	g++ -Wall -Wextra -pedantic -std=c++11 -O3 -g -o burncycles burncycles.cc

besleepy: besleepy.cc
	g++ -Wall -Wextra -pedantic -std=c++11 -O3 -g -o besleepy besleepy.cc

clean:
	rm -f alloclots burncycles
